name: PR
on:
  pull_request:
    branches:
      - main
jobs:
  format:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Setup Nix and Cachix
        uses: ./.github/actions/setup-nix.yml
      - name: Format Check
        uses: ./.github/actions/format.yml
  check:
    runs-on: ubuntu-latest
    needs: format
    strategy:
      fail-fast: false
      matrix:
        host: [drakkar, huginn, mimir, muninn]
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Setup Nix and Cachix
        uses: ./.github/actions/setup-nix.yml
      - name: Check
        uses: ./.github/actions/check.yml
        with:
          host: ${{ matrix.host }}
